version: '3.7'

services:
  db:
    image: mongo:3.6-xenial
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - dbdata:/data/db
    networks:
      - app-network
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend
    container_name: backend
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=db
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=social_db
      - SECRET_KEY=$SECRET_KEY
      - BACKEND_PORT=$BACKEND_PORT
    ports:
      - '5000:5000'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network
    command: ./wait-for.sh db:27017 -- nodemon index.js
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: frontend
    container_name: frontend
    depends_on: 
      - backend
    env_file: ./client/.env
    environment:
      - REACT_APP_BACKEND_HOST=backend
      - REACT_APP_BACKEND_PORT=5000
    ports:
      - '1337:80'
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  dbdata:
  node_modules: